### ISSUE TITLE
Zookeeper is creating too large temporary files

### ISSUE THREAD

**Issue by roberto-isi** [jacamo-lang/jacamo-rest#31]
When you acess the Temp folder from zookeeper, it automatically creates a LOG with about 60mb each time it runs!! Running a lot of time in a day can produce some gigabytes of log

On windows the folder is
drive:/users/{your_user}/AppData/Local/Temp

The folder with logs are named like: zookeeper3897398712893712993871289

Thanks

**Comment by jomifred** [comment]
could you please post here an excerpt of the log file content? trying to identify the message that is being repeated?

**Comment by roberto-isi** [comment]
I cannot say because the log is not a text file!! Its encrypted!!
 
Inside the principal folder have a folder named "version-2" an inside of it two files: "log.1" and "snapshot.0" !!!

When i try to open like a text its encrypted!

Sometimes have some trashes like this:
p!H(*      /jacamo/agents            world   anyone    B    5
/jacamo/df            world   anyone    B
