### ISSUE TITLE
Change POST methods for creating items to return 201

### ISSUE THREAD

**Issue by cleberjamaral** [jacamo-lang/jacamo-rest#36]
As a standard, a POST should return 201 (Created). Source: https://restfulapi.net/http-methods/

**Comment by jomifred** [comment]
In the code we are using "return Response.ok().build();". Doesn't it handle the answer properly?

**Comment by cleberjamaral** [comment]
When the link cannot be provided 200 is often used. It is the case of /cmd and /mb (code 202 - accepted also seems to be good)

In case of creating items ideally, code 201 is used. I suggest the it as a standard following this example (return of creating an agent):

return Response.created(new URI("/agents/" + givenName)).build();

**Comment by TimKam** [comment]
Should probably be: https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Response.Status.html#CREATED.

**Comment by cleberjamaral** [comment]
All post that create resources are now generating 201. From the postman documentation, the other posts we have (rpc-like) should actually return 202 (accepted). Anyway, I am going to close this issue.
