### ISSUE TITLE
Change URIs for new 0.5 API proposal

### ISSUE THREAD

**Issue by cleberjamaral** [jacamo-lang/jacamo-rest#37]
A draft of the API 0.5 is on the readme.md (https://github.com/jacamo-lang/jacamo-rest/). It intends to provide enough information to infer any URI of other resources. 

Right now we are based on OPTIONS methods that already provide info to third-party agents navigate through jacamo-rest. It means, we are not going to provide links in this version. 

It is important to mention that links can improve navigability but there is no standard to provide information about methods to apply on links. Using links it is not clear how we could provide navigability to /command endpoint, for instance. Links sound to fit very well APIs that have only CRUD-like endpoints.

**Comment by jomifred** [comment]
Detalhe, arrumei umas coisas na 0.4, na classe java RestAgArch.
Como isso se propaga no branch da 0.5 onde essa classe foi parar em outro pacote? Tu sabe com ligar com isso?

**Comment by cleberjamaral** [comment]
It was changed but many endpoints of the original proposal for version 0.5 were moved to version 0.6.
